In [66]:
#Importing Libraries 
import numpy as np
import pandas as pd

#importing visualization
import matplotlib.pyplot as plt
import seaborn as sb

#importing metrics
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [67]:
#importing data
data = pd.read_csv('cancer.csv')

In [68]:
data.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [69]:
#checking shape
data.shape

(569, 33)

In [70]:
#Eliminating unused columns
data = data.iloc[:,1:31]

In [71]:
data.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  fractal_dimension_se  radius_worst  texture_worst  \
0         0.2419  ...              0.006193         25.38          17.33   
1         0.1812  ...              0.003532         24.99          23.41   
2         0.2069  ...              0.004571         23.57          25.53   
3         0.2597  ...              0.009208         14.91          26.50   
4         0.1809  ...              0.005115         22.54          16.67   

   perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
0           184.60      2019.0            0.1622             0.6656   
1           158.80      1956.0            0.1238             0.1866   
2           152.50      1709.0            0.1444             0.4245   
3            98.87       567.7            0.2098             0.8663   
4           152.20      1575.0            0.1374             0.2050   

   concavity_worst  concave points_worst  symmetry_worst  
0           0.7119                0.2654          0.4601  
1           0.2416                0.1860          0.2750  
2           0.4504                0.2430          0.3613  
3           0.6869                0.2575          0.6638  
4           0.4000                0.1625          0.2364  

[5 rows x 30 columns]

In [72]:
#changing catagorical data to numeric data
from sklearn.preprocessing import LabelEncoder

In [73]:
enc = LabelEncoder()

In [74]:
data.diagnosis = enc.fit_transform(data.diagnosis)

In [75]:
data.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0          1        17.99         10.38          122.80     1001.0   
1          1        20.57         17.77          132.90     1326.0   
2          1        19.69         21.25          130.00     1203.0   
3          1        11.42         20.38           77.58      386.1   
4          1        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  fractal_dimension_se  radius_worst  texture_worst  \
0         0.2419  ...              0.006193         25.38          17.33   
1         0.1812  ...              0.003532         24.99          23.41   
2         0.2069  ...              0.004571         23.57          25.53   
3         0.2597  ...              0.009208         14.91          26.50   
4         0.1809  ...              0.005115         22.54          16.67   

   perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
0           184.60      2019.0            0.1622             0.6656   
1           158.80      1956.0            0.1238             0.1866   
2           152.50      1709.0            0.1444             0.4245   
3            98.87       567.7            0.2098             0.8663   
4           152.20      1575.0            0.1374             0.2050   

   concavity_worst  concave points_worst  symmetry_worst  
0           0.7119                0.2654          0.4601  
1           0.2416                0.1860          0.2750  
2           0.4504                0.2430          0.3613  
3           0.6869                0.2575          0.6638  
4           0.4000                0.1625          0.2364  

[5 rows x 30 columns]

In [76]:
Y = data.diagnosis
X = data.iloc[:,1:30:2]

In [77]:
#importing train_test_split
from sklearn.model_selection import train_test_split

In [78]:
#Training X and Y values
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.20,random_state=50)

## Logistic Regression

In [79]:
from sklearn.linear_model import LogisticRegression

In [80]:
model_lr = LogisticRegression()

In [81]:
model_lr.fit(X_train,Y_train)

C:\Users\abhishek\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [82]:
predict_lr = model_lr.predict(X_test)

In [83]:
Y_test.head()

356    0
556    0
283    1
495    0
364    0
Name: diagnosis, dtype: int32

In [84]:
predict_lr

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 0])

In [85]:
#checking accuracy score and confusion matrix

In [86]:
accuracy_score(Y_test,predict_lr)

0.9298245614035088

In [87]:
confusion_matrix(Y_test,predict_lr)

array([[70,  5],
       [ 3, 36]], dtype=int64)

## k nearest neighbour 


In [88]:
from sklearn.neighbors import KNeighborsClassifier

In [89]:
model_knn = KNeighborsClassifier(n_neighbors=7)

In [90]:
model_knn.fit(X_train,Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=7, p=2,
           weights='uniform')

In [91]:
predict_knn = model_knn.predict(X_test)

In [92]:
Y_test.head()

356    0
556    0
283    1
495    0
364    0
Name: diagnosis, dtype: int32

In [93]:
predict_knn

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 0])

In [94]:
#accuracy score and classification report

In [95]:
accuracy_score(Y_test,predict_knn)

0.9385964912280702

In [96]:
print(classification_report(Y_test,predict_knn))

## 

              precision    recall  f1-score   support

           0       0.95      0.96      0.95        75
           1       0.92      0.90      0.91        39

   micro avg       0.94      0.94      0.94       114
   macro avg       0.93      0.93      0.93       114
weighted avg       0.94      0.94      0.94       114



## Support Vector Classification

In [97]:
from sklearn.svm import SVC

In [98]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.20,random_state=50)

In [99]:
model_svc = SVC(kernel = 'rbf', gamma = 0.09, C = 1000)

In [100]:
model_svc.fit(X_train,Y_train)

SVC(C=1000, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.09, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [101]:
predict_svc = model_svc.predict(X_test)

In [102]:
accuracy_score(Y_test,predict_svc)

0.9210526315789473

In [103]:
#checking the best parameters

In [104]:
parameters = [{'kernel':['linear'],'C':[1,10,100,1000,10000]},{'kernel':['rbf'],'gamma':[0.5,0.1,0.05,0.07,0.08],'C':[1,10,100,1000,10000]}]

In [105]:
from sklearn.model_selection import GridSearchCV

In [106]:
model_grid_svc = GridSearchCV(SVC(),parameters)

In [107]:
model_grid_svc.fit(X_train,Y_train)

C:\Users\abhishek\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)


GridSearchCV(cv='warn', error_score='raise-deprecating',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid=[{'kernel': ['linear'], 'C': [1, 10, 100, 1000, 10000]}, {'kernel': ['rbf'], 'gamma': [0.5, 0.1, 0.05, 0.07, 0.08], 'C': [1, 10, 100, 1000, 10000]}],
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [108]:
# Best Score

In [109]:
model_grid_svc.best_score_

0.9494505494505494

In [110]:
model_grid_svc.best_params_

{'C': 1, 'kernel': 'linear'}

## Deceision Tree

In [111]:
from sklearn.tree import DecisionTreeClassifier

In [112]:
model_dt = DecisionTreeClassifier()

In [113]:
model_dt.fit(X_train,Y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [114]:
predict_dt = model_dt.predict(X_test)

In [115]:
accuracy_score(Y_test,predict_dt)

0.9298245614035088

In [116]:
print(classification_report(Y_test,predict_dt))

              precision    recall  f1-score   support

           0       0.95      0.95      0.95        75
           1       0.90      0.90      0.90        39

   micro avg       0.93      0.93      0.93       114
   macro avg       0.92      0.92      0.92       114
weighted avg       0.93      0.93      0.93       114



## Random Forest 

In [117]:
from sklearn.ensemble import RandomForestClassifier

In [118]:
model_rf = RandomForestClassifier()

In [119]:
model_rf.fit(X_train,Y_train)

C:\Users\abhishek\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [120]:
predict_rf = model_rf.predict(X_test)

In [121]:
accuracy_score(Y_test,predict_rf)

0.956140350877193

In [122]:
print(classification_report(Y_test,predict_rf))

              precision    recall  f1-score   support

           0       0.97      0.96      0.97        75
           1       0.93      0.95      0.94        39

   micro avg       0.96      0.96      0.96       114
   macro avg       0.95      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114



## XGBoost 

In [123]:
from xgboost import XGBClassifier

In [124]:
model_xgb = XGBClassifier()

In [125]:
model_xgb.fit(X_train,Y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bynode=1, colsample_bytree=1, gamma=0, learning_rate=0.1,
       max_delta_step=0, max_depth=3, min_child_weight=1, missing=None,
       n_estimators=100, n_jobs=1, nthread=None,
       objective='binary:logistic', random_state=0, reg_alpha=0,
       reg_lambda=1, scale_pos_weight=1, seed=None, silent=None,
       subsample=1, verbosity=1)

In [126]:
predict_xgb = model_xgb.predict(X_test)

In [127]:
accuracy_score(Y_test,predict_xgb)

0.956140350877193

In [128]:
confusion_matrix(Y_test,predict_xgb)

array([[72,  3],
       [ 2, 37]], dtype=int64)